version: '3'
services:
  inqueue:
    image: "rabbitmq:3"
    hostname: "inqueue"
    ports:
      - "5672:5672"
    labels:
      NAME: "spam-inqueue"
  outqueue:
    image: "rabbitmq:3"
    hostname: "outqueue"
    ports:
      - "5673:5672"
    labels:
      NAME: "spam-outqueue"